Algoritmo "20-apostila"
//Ler dois valores (considere que não serão lidos valores iguais) e escrevê-los
//em ordem crescente.
Var
a,b:inteiro


Inicio
escreva("A= ")
leia(a)
escreva("B= ")
leia(b)
       se a = b então
          escreva("Os valores são iguais.")
       senao
            se a>b entao
               escreva("A ordem crescente é:",b," e ",a)
            senao
                 escreva("A ordem crescente é:",a," e ",b)
       fimse
            fimse
Fimalgoritmo