Algoritmo "semnome"
//Ler 3 valores (considere que não serão informados valores iguais)
//e escrever o maior deles.
Var
a,b,c:inteiro

Inicio
escreva("A= ")
leia(a)
escreva("B= ")
leia(b)
escreva("C= ")
leia(c)
se (a > b) e (a > c)entao
escreva("A é maior")
senao
fimse
se (b > a) e (b > c)entao
escreva("B é maior")
senao
fimse
se (c > a) e (c > b)entao
escreva("C é maior")
senao
fimse

Fimalgoritmo