Algoritmo "33-apostila"
//Ler dois valores e imprimir uma das três mensagens a seguir: ‘
//Números iguais’, caso os números sejam iguais
//‘Primeiro é maior’, caso o primeiro seja maior que o segundo;
//‘Segundo maior’, caso o segundo seja maior que o primeiro.
Var
a,b: inteiro

Inicio
escreva("A= ")
leia(a)
escreva("B= ")
leia(b)
se a=b entao
escreva("Numeros iguais")
senao
se a>b entao
escreva("A é maior")
senao
escreva("B é maior")
fimse
fimse

Fimalgoritmo