Algoritmo "44-apostila"
//Escreva um algoritmo para ler 2 valores
//e se o segundo valor informado for ZERO, deve ser lido um novo valor,
//ou seja, para o segundo valor não pode ser aceito o valor zero
//e imprimir o resultado da divisão do primeiro valor lido pelo segundo valor
//lido.

//(utilizar a estrutura REPITA).


Var
a,b:inteiro


Inicio
escreva("A= ")
leia(a)
escreva("B= ")
leia(b)
se a = 0 entao

Fimalgoritmo