Algoritmo "02-lista3"
//Elaborar um programa que calcule e apresente o volume de uma caixa retangular,
//por meio da fórmula VOLUME=COMPRIMENTO * LARGURA * ALTURA.
Var
volume, comprimento, largura, altura: real


Inicio
escreva("Comprimento= ")
leia(comprimento)
escreva("Largura= ")
leia(largura)
escreva("Altura= ")
leia(altura)
volume:= comprimento * largura *altura
escreva("Volume= ", volume)

Fimalgoritmo