Algoritmo "03-lista3"
//Ler dois inteiros (variáveis A e B) e imprimir o resultado do quadrado da
//diferença do primeiro valor pelo segundo.
Var
valorUm, valorDois, resultado, diferenca: inteiro


Inicio
escreva("Primeiro valor= ")
leia(valorUm)
escreva("Segundo valor= ")
leia(valorDois)
diferenca:= valorUm-valorDois
resultado:= diferenca*diferenca
escreva("A diferença é: ", diferenca)


Fimalgoritmo