Algoritmo "07-lista3"
//Elaborar um programa que efetue a leitura de três valores (A, B e C) e apresente
//como resultado final o quadrado da soma dos três valores lidos.
Var
a, b, c, resultado, quadrado:inteiro


Inicio
escreva("A= ")
leia(a)
escreva("B= ")
leia(b)
escreva("C= ")
leia(c)
resultado:= a+b+c
quadrado:= (resultado*resultado)
escreva("Resultado: ",quadrado)
Fimalgoritmo