Algoritmo "semnome"
// Elaborar um programa que apresente os valores de conversão de graus Celsius em Fahrenheit, de
//10 em 10 graus, iniciando a contagem em 10 graus Celsius e finalizando em 100 graus Celsius. O
//programa deve apresentar os valores das duas temperaturas.
Var
c:inteiro
f:real
Inicio
para c de 10 ate 100 passo 10 faca
f:= (c*9+160)/5
escreval("Fahrenheit = ",f)
fimpara
Fimalgoritmo