Algoritmo "numero sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Escreva um algoritmo para ler um valor do teclado e exibir
// como resposta o número sucessor.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2022
Var
n1:inteiro
resultado: inteiro

Inicio
escreval("Digite um numero:")
leia(n1)
resultado:= n1+1
escreva("O numero sucessor é", resultado)


Fimalgoritmo