Algoritmo "raio circular"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Escreva um algoritmo para ler as dimensões de um circulo (raio),
//               calcular e escrever a área do circulo. a=pi*r²
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2022
Var
area, raio: real
Inicio

escreva("Raio:")
leia(raio)
area:= 3.14*(raio*raio)
escreva("A area é:",area)

Fimalgoritmo